org: pustaka
app: pustaka-node-new
service: author-dashboard

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: src/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-plugin-typescript

package:
  individually: true
  patterns:
    [
      "src/generated/client/schema.prisma",
      "!src/generated/client/libquery_engine-*",
      "src/generated/client/libquery_engine-rhel-*",
      "!node_modules/prisma/libquery_engine-*",
      "!node_modules/@prisma/engines/**",
    ]
